# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_denglu(object):
    def setupUi(self, MainWindow_denglu):
        MainWindow_denglu.setObjectName("MainWindow_denglu")
        MainWindow_denglu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_denglu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 140, 221, 421))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 140, 551, 421))
        self.label_2.setStyleSheet("border-image: url(:/images/images/pexels-padrinan-19670.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 140, 551, 421))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 100);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 131, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 290, 131, 41))
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 360, 131, 41))
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_denglu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_denglu.setGeometry(QtCore.QRect(80, 460, 81, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_denglu.setFont(font)
        self.pushButton_denglu.setStyleSheet("QPushButton{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_denglu.setObjectName("pushButton_denglu")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(700, 150, 66, 41))
        self.frame.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setStyleSheet("")
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/qtexe_images/缩小.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/关白粗.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 230, 311, 111))
        font = QtGui.QFont()
        font.setFamily("Tiger Expert")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.pushButton_chuce = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_chuce.setGeometry(QtCore.QRect(90, 510, 61, 23))
        self.pushButton_chuce.setStyleSheet("QPushButton{\n"
"\n"
"    border:none;\n"
"}")
        self.pushButton_chuce.setObjectName("pushButton_chuce")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_denglu.raise_()
        self.label_5.raise_()
        self.pushButton_chuce.raise_()
        self.frame.raise_()
        MainWindow_denglu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_denglu)
        self.pushButton_3.clicked.connect(MainWindow_denglu.close) # type: ignore
        self.pushButton_2.clicked.connect(MainWindow_denglu.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow_denglu)

    def retranslateUi(self, MainWindow_denglu):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_denglu.setWindowTitle(_translate("MainWindow_denglu", "MainWindow"))
        self.label_4.setText(_translate("MainWindow_denglu", "欢迎登录"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow_denglu", "账号："))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow_denglu", "密码："))
        self.pushButton_denglu.setText(_translate("MainWindow_denglu", "登录"))
        self.label_5.setText(_translate("MainWindow_denglu", "风氢规划\n"
"\n"
"综合管理平台"))
        self.pushButton_chuce.setText(_translate("MainWindow_denglu", "注册"))
import res_rc
