# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zhuce.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_zhuce(object):
    def setupUi(self, MainWindow_zhuce):
        MainWindow_zhuce.setObjectName("MainWindow_zhuce")
        MainWindow_zhuce.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow_zhuce)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 60, 361, 421))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 260, 131, 41))
        self.lineEdit_2.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 200, 131, 41))
        self.lineEdit.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_zhuce = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zhuce.setGeometry(QtCore.QRect(400, 400, 81, 41))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_zhuce.setFont(font)
        self.pushButton_zhuce.setStyleSheet("QPushButton{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_zhuce.setObjectName("pushButton_zhuce")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(370, 130, 131, 51))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 320, 131, 41))
        self.lineEdit_3.setStyleSheet("border:none;\n"
"border-bottom: 2px solid rgba(0, 0, 0, 100);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(80, 160, 82, 44))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_fanhui = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_fanhui.setGeometry(QtCore.QRect(270, 80, 81, 21))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_fanhui.setFont(font)
        self.pushButton_fanhui.setStyleSheet("QPushButton{\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(102, 133, 156, 255), stop:1 rgba(117, 255, 201, 255));\n"
"    color:rgb(255, 255, 255);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"}")
        self.pushButton_fanhui.setObjectName("pushButton_fanhui")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(550, 80, 46, 31))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}\n"
"")
        self.pushButton_8.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/qtexe_images/叉.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setObjectName("pushButton_8")
        MainWindow_zhuce.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_zhuce)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_zhuce)

    def retranslateUi(self, MainWindow_zhuce):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_zhuce.setWindowTitle(_translate("MainWindow_zhuce", "MainWindow"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow_zhuce", "账号密码："))
        self.lineEdit.setPlaceholderText(_translate("MainWindow_zhuce", "账号名称："))
        self.pushButton_zhuce.setText(_translate("MainWindow_zhuce", "注册"))
        self.label_5.setText(_translate("MainWindow_zhuce", "账号注册"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow_zhuce", "确认密码："))
        self.pushButton_fanhui.setText(_translate("MainWindow_zhuce", "返回登录界面"))
import res_rc
